services:
  _defaults:
    public: true #DOESN'T allow optimizing the container by removing unused services
    autowire: true
    autoconfigure: true

  Log\:
    resource: '../src/'
    exclude:
      - '../src/Tests/'
      - '../src/Entity/'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'app.command' ]
